test trigger of ubi update

diff --git a/.github/workflows/ubi-version-update.yaml b/.github/workflows/ubi-version-update.yaml
--- a/.github/workflows/ubi-version-update.yaml
+++ b/.github/workflows/ubi-version-update.yaml
@@ -49,7 +49,7 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v4
 
-    - name: Check if Skopeo is installed
+    - name: Install dependencies
       id: check-skopeo
       run: |
         if ! command -v skopeo &> /dev/null; then
@@ -59,6 +59,15 @@ jobs:
         else
           echo "Skopeo is already installed"
         fi
+        
+        if ! command -v jq&> /dev/null; then
+          echo "jq not found, installing..."
+          sudo apt-get update
+          sudo apt-get install -y jq
+        else
+          echo "jq is already installed"
+        fi
+
 
     - name: Fetch latest UBI9 micro image SHA
       id: fetch-sha
